# COUNT=0;
# for i in {0..100}
# do
#     (cp -rf template_project project_$COUNT);
#     COUNT=$(( $COUNT + 1 ));
# done

cp -rf template_project project_1_00
cp -rf template_project project_1_01
cp -rf template_project project_1_02
cp -rf template_project project_1_03
cp -rf template_project project_1_04
cp -rf template_project project_1_05
cp -rf template_project project_1_06
cp -rf template_project project_1_07
cp -rf template_project project_1_08
cp -rf template_project project_1_09
cp -rf template_project project_1_10
cp -rf template_project project_1_11
cp -rf template_project project_1_12
cp -rf template_project project_1_13
cp -rf template_project project_1_14
cp -rf template_project project_1_15
cp -rf template_project project_1_16
cp -rf template_project project_1_17
cp -rf template_project project_1_18
cp -rf template_project project_1_19
cp -rf template_project project_1_20
cp -rf template_project project_1_21
cp -rf template_project project_1_22
cp -rf template_project project_1_23
cp -rf template_project project_1_24
cp -rf template_project project_1_25
cp -rf template_project project_1_26
cp -rf template_project project_1_27
cp -rf template_project project_1_28
cp -rf template_project project_1_29
cp -rf template_project project_1_30
cp -rf template_project project_1_31
cp -rf template_project project_1_32
cp -rf template_project project_1_33
cp -rf template_project project_1_34
cp -rf template_project project_1_35
cp -rf template_project project_1_36
cp -rf template_project project_1_37
cp -rf template_project project_1_38
cp -rf template_project project_1_39
cp -rf template_project project_1_40
cp -rf template_project project_1_41
cp -rf template_project project_1_42
cp -rf template_project project_1_43
cp -rf template_project project_1_44
cp -rf template_project project_1_45
cp -rf template_project project_1_46
cp -rf template_project project_1_47
cp -rf template_project project_1_48
cp -rf template_project project_1_49
cp -rf template_project project_1_50
cp -rf template_project project_1_51
cp -rf template_project project_1_52
cp -rf template_project project_1_53
cp -rf template_project project_1_54
cp -rf template_project project_1_55
cp -rf template_project project_1_56
cp -rf template_project project_1_57
cp -rf template_project project_1_58
cp -rf template_project project_1_59
cp -rf template_project project_1_60
cp -rf template_project project_1_61
cp -rf template_project project_1_62
cp -rf template_project project_1_63
cp -rf template_project project_1_64
cp -rf template_project project_1_65
cp -rf template_project project_1_66
cp -rf template_project project_1_67
cp -rf template_project project_1_68
cp -rf template_project project_1_69
cp -rf template_project project_1_70
cp -rf template_project project_1_71
cp -rf template_project project_1_72
cp -rf template_project project_1_73
cp -rf template_project project_1_74
cp -rf template_project project_1_75
cp -rf template_project project_1_76
cp -rf template_project project_1_77
cp -rf template_project project_1_78
cp -rf template_project project_1_79
cp -rf template_project project_1_80
cp -rf template_project project_1_81
cp -rf template_project project_1_82
cp -rf template_project project_1_83
cp -rf template_project project_1_84
cp -rf template_project project_1_85
cp -rf template_project project_1_86
cp -rf template_project project_1_87
cp -rf template_project project_1_88
cp -rf template_project project_1_89
cp -rf template_project project_1_90
cp -rf template_project project_1_91
cp -rf template_project project_1_92
cp -rf template_project project_1_93
cp -rf template_project project_1_94
cp -rf template_project project_1_95
cp -rf template_project project_1_96
cp -rf template_project project_1_97
cp -rf template_project project_1_98
cp -rf template_project project_1_99
cp -rf template_project project_2_00
cp -rf template_project project_2_01
cp -rf template_project project_2_02
cp -rf template_project project_2_03
cp -rf template_project project_2_04
cp -rf template_project project_2_05
cp -rf template_project project_2_06
cp -rf template_project project_2_07
cp -rf template_project project_2_08
cp -rf template_project project_2_09
cp -rf template_project project_2_10
cp -rf template_project project_2_11
cp -rf template_project project_2_12
cp -rf template_project project_2_13
cp -rf template_project project_2_14
cp -rf template_project project_2_15
cp -rf template_project project_2_16
cp -rf template_project project_2_17
cp -rf template_project project_2_18
cp -rf template_project project_2_19
cp -rf template_project project_2_20
cp -rf template_project project_2_21
cp -rf template_project project_2_22
cp -rf template_project project_2_23
cp -rf template_project project_2_24
cp -rf template_project project_2_25
cp -rf template_project project_2_26
cp -rf template_project project_2_27
cp -rf template_project project_2_28
cp -rf template_project project_2_29
cp -rf template_project project_2_30
cp -rf template_project project_2_31
cp -rf template_project project_2_32
cp -rf template_project project_2_33
cp -rf template_project project_2_34
cp -rf template_project project_2_35
cp -rf template_project project_2_36
cp -rf template_project project_2_37
cp -rf template_project project_2_38
cp -rf template_project project_2_39
cp -rf template_project project_2_40
cp -rf template_project project_2_41
cp -rf template_project project_2_42
cp -rf template_project project_2_43
cp -rf template_project project_2_44
cp -rf template_project project_2_45
cp -rf template_project project_2_46
cp -rf template_project project_2_47
cp -rf template_project project_2_48
cp -rf template_project project_2_49
cp -rf template_project project_2_50
cp -rf template_project project_2_51
cp -rf template_project project_2_52
cp -rf template_project project_2_53
cp -rf template_project project_2_54
cp -rf template_project project_2_55
cp -rf template_project project_2_56
cp -rf template_project project_2_57
cp -rf template_project project_2_58
cp -rf template_project project_2_59
cp -rf template_project project_2_60
cp -rf template_project project_2_61
cp -rf template_project project_2_62
cp -rf template_project project_2_63
cp -rf template_project project_2_64
cp -rf template_project project_2_65
cp -rf template_project project_2_66
cp -rf template_project project_2_67
cp -rf template_project project_2_68
cp -rf template_project project_2_69
cp -rf template_project project_2_70
cp -rf template_project project_2_71
cp -rf template_project project_2_72
cp -rf template_project project_2_73
cp -rf template_project project_2_74
cp -rf template_project project_2_75
cp -rf template_project project_2_76
cp -rf template_project project_2_77
cp -rf template_project project_2_78
cp -rf template_project project_2_79
cp -rf template_project project_2_80
cp -rf template_project project_2_81
cp -rf template_project project_2_82
cp -rf template_project project_2_83
cp -rf template_project project_2_84
cp -rf template_project project_2_85
cp -rf template_project project_2_86
cp -rf template_project project_2_87
cp -rf template_project project_2_88
cp -rf template_project project_2_89
cp -rf template_project project_2_90
cp -rf template_project project_2_91
cp -rf template_project project_2_92
cp -rf template_project project_2_93
cp -rf template_project project_2_94
cp -rf template_project project_2_95
cp -rf template_project project_2_96
cp -rf template_project project_2_97
cp -rf template_project project_2_98
cp -rf template_project project_2_99